/**********************************************************************
artefact name :- d_customer
description   :- d_customer sql generated via multi-pass CTE pipeline
----------------------------------------------------------------------
change log
version :   date :        description :                       changed by
----------------------------------------------------------------------
0.0         2026-06-21    auto-generated multi-pass            ai_agent
**********************************************************************/

with
ad_mstr_cte as (
    select 
    concat('msd_qad_', lower(ad_mstr.ad_domain)) || '|' || ad_mstr.ad_addr as cust_key,
    concat('msd_qad_', lower(ad_mstr.ad_domain)) || '|' || ad_mstr.ad_addr as src_sys_cd,
    cm_mstr.cm_addr as cust_id,
    ad_mstr.ad_name as cust_nm,
    ad_mstr.ad_name as cust_nm_en,
    ad_mstr.ad_type as cust_type_cd,
    ad_mstr.ad_type as cust_type_nm,
    cast(null as string) as active_flg,
    cast(null as string) as parent_cust_id,
    cast(null as string) as parent_cust_nm,
    cast(null as string) as naics_cd,
    cast(null as string) as naics_nm,
    cast(null as string) as sic_cd,
    cast(null as string) as sic_nm,
    cast(null as string) as gbl_govt_id,
    cast(null as string) as gbl_loc_nbr,
    cast(null as string) as dnb_duns_nm,
    cast(null as string) as alt_payer_cust_id,
    cast(null as string) as annl_sls_amt,
    cast(null as string) as central_bill_block_cd,
    current_timestamp as rec_crt_ts,
    current_timestamp as rec_updt_ts
from ad_mstr
left join cm_mstr 
    on upper(cm_mstr.cm_addr) = upper(ad_mstr.ad_addr) 
    and upper(cm_mstr.cm_domain) = upper(ad_mstr.ad_domain)
),
cm_mstr_cte as (
    select
    concat('msd_qad_', lower(ad_mstr.ad_domain)) || '|' || ad_mstr.ad_addr as cust_key,
    concat('msd_qad_', lower(ad_mstr.ad_domain)) || '|' || ad_mstr.ad_addr as src_sys_cd,
    cm_mstr.cm_addr as cust_id,
    ad_mstr.ad_name as cust_nm,
    ad_mstr.ad_name as cust_nm_en,
    ad_mstr.ad_type as cust_type_cd,
    ad_mstr.ad_type as cust_type_nm,
    cast(null as string) as active_flg,
    cast(null as string) as parent_cust_id,
    cast(null as string) as parent_cust_nm,
    cast(null as string) as naics_cd,
    cast(null as string) as naics_nm,
    cast(null as string) as sic_cd,
    cast(null as string) as sic_nm,
    cast(null as string) as gbl_govt_id,
    cast(null as string) as gbl_loc_nbr,
    cast(null as string) as dnb_duns_nm,
    cast(null as string) as alt_payer_cust_id,
    cast(null as string) as annl_sls_amt,
    cast(null as string) as central_bill_block_cd,
    current_timestamp as rec_crt_ts,
    current_timestamp as rec_updt_ts
from cm_mstr
left join ad_mstr
    on upper(cm_mstr.cm_addr) = upper(ad_mstr.ad_addr)
    and upper(cm_mstr.cm_domain) = upper(ad_mstr.ad_domain)
),
currency_cte as (
    select 
    cm_mstr.cm_curr as curncy_cd,
    currency.currencydescription as curncy_nm,
    current_timestamp as rec_crt_ts,
    current_timestamp as rec_updt_ts
from 
    cm_mstr
left join 
    currency 
on 
    currency.currencycode = cm_mstr.cm_curr
),
d_cntry_hier_cte as (
    select
    concat('msd_qad_', lower(ad_mstr.ad_domain)) || '|' || ad_mstr.ad_addr as cust_key,
    concat('msd_qad_', lower(ad_mstr.ad_domain)) as src_sys_cd,
    cm_mstr.cm_addr as cust_id,
    ad_mstr.ad_name as cust_nm,
    ad_mstr.ad_name as cust_nm_en,
    ad_mstr.ad_type as cust_type_cd,
    ad_mstr.ad_type as cust_type_nm,
    cast(null as string) as active_flg,
    cast(null as string) as parent_cust_id,
    cast(null as string) as parent_cust_nm,
    cast(null as string) as naics_cd,
    cast(null as string) as naics_nm,
    cast(null as string) as sic_cd,
    cast(null as string) as sic_nm,
    cast(null as string) as gbl_govt_id,
    cast(null as string) as gbl_loc_nbr,
    cast(null as string) as dnb_duns_nm,
    cast(null as string) as alt_payer_cust_id,
    cast(null as string) as annl_sls_amt,
    cast(null as string) as central_bill_block_cd,
    current_timestamp as rec_crt_ts,
    current_timestamp as rec_updt_ts
from ad_mstr
left join cm_mstr
    on upper(cm_mstr.cm_addr) = upper(ad_mstr.ad_addr)
    and upper(cm_mstr.cm_domain) = upper(ad_mstr.ad_domain)
inner join d_cntry_hier
    on upper(ad_mstr.ad_ctry) = upper(d_cntry_hier.cntry_alpha2_cd)
),
cust_type_mapping_cte as (
    select 
    concat('msd_qad_', lower(ad_mstr.ad_domain)) || '|' || ad_mstr.ad_addr as cust_key,
    concat('msd_qad_', lower(ad_mstr.ad_domain)) as src_sys_cd,
    cm_mstr.cm_addr as cust_id,
    ad_mstr.ad_name as cust_nm,
    ad_mstr.ad_name as cust_nm_en,
    ad_mstr.ad_type as cust_type_cd,
    ad_mstr.ad_type as cust_type_nm,
    cast(null as string) as active_flg,
    cast(null as string) as parent_cust_id,
    cast(null as string) as parent_cust_nm,
    cast(null as string) as naics_cd,
    cast(null as string) as naics_nm,
    cast(null as string) as sic_cd,
    cast(null as string) as sic_nm,
    cast(null as string) as gbl_govt_id,
    cast(null as string) as gbl_loc_nbr,
    cast(null as string) as dnb_duns_nm,
    cast(null as string) as alt_payer_cust_id,
    cast(null as string) as annl_sls_amt,
    cast(null as string) as central_bill_block_cd,
    current_timestamp as rec_crt_ts,
    current_timestamp as rec_updt_ts
from ad_mstr
left join cm_mstr 
    on upper(cm_mstr.cm_addr) = upper(ad_mstr.ad_addr) 
    and upper(cm_mstr.cm_domain) = upper(ad_mstr.ad_domain)
),
active_flag_cte as (
    select 
    concat('msd_qad_', lower(ad_mstr.ad_domain)) || '|' || ad_mstr.ad_addr as cust_key,
    concat('msd_qad_', lower(ad_mstr.ad_domain)) as src_sys_cd,
    cm_mstr.cm_addr as cust_id,
    ad_mstr.ad_name as cust_nm,
    ad_mstr.ad_name as cust_nm_en,
    ad_mstr.ad_type as cust_type_cd,
    ad_mstr.ad_type as cust_type_nm,
    case 
        when upper(ad_mstr.ad_status) = 'ACTIVE' then 'Y'
        else 'N'
    end as active_flg,
    cast(null as string) as parent_cust_id,
    cast(null as string) as parent_cust_nm,
    cast(null as string) as naics_cd,
    cast(null as string) as naics_nm,
    cast(null as string) as sic_cd,
    cast(null as string) as sic_nm,
    cast(null as string) as gbl_govt_id,
    cast(null as string) as gbl_loc_nbr,
    cast(null as string) as dnb_duns_nm,
    cast(null as string) as alt_payer_cust_id,
    cast(null as string) as annl_sls_amt,
    cast(null as string) as central_bill_block_cd,
    current_timestamp as rec_crt_ts,
    current_timestamp as rec_updt_ts
from ad_mstr
left join cm_mstr 
    on upper(cm_mstr.cm_addr) = upper(ad_mstr.ad_addr) 
    and upper(cm_mstr.cm_domain) = upper(ad_mstr.ad_domain)
),
final_joined_cte as (
    select
    concat('msd_qad_', lower(ad_mstr.ad_domain)) || '|' || ad_mstr.ad_addr as cust_key,
    concat('msd_qad_', lower(ad_mstr.ad_domain)) as src_sys_cd,
    cm_mstr.cm_addr as cust_id,
    ad_mstr.ad_name as cust_nm,
    ad_mstr.ad_name as cust_nm_en,
    ad_mstr.ad_type as cust_type_cd,
    ad_mstr.ad_type as cust_type_nm,
    cast(null as string) as active_flg,
    cast(null as string) as parent_cust_id,
    cast(null as string) as parent_cust_nm,
    cast(null as string) as naics_cd,
    cast(null as string) as naics_nm,
    cast(null as string) as sic_cd,
    cast(null as string) as sic_nm,
    cast(null as string) as gbl_govt_id,
    cast(null as string) as gbl_loc_nbr,
    cast(null as string) as dnb_duns_nm,
    cast(null as string) as alt_payer_cust_id,
    cast(null as string) as annl_sls_amt,
    cast(null as string) as central_bill_block_cd,
    cast(null as string) as central_bill_block_nm,
    cast(null as string) as central_delvr_block_cd,
    cast(null as string) as central_delvr_block_nm,
    cast(null as string) as central_ord_block_cd,
    cast(null as string) as central_ord_block_nm,
    cast(null as string) as cust_acct_grp_cd,
    cast(null as string) as cust_acct_grp_nm,
    cast(null as string) as cust_class_cd,
    cast(null as string) as cust_class_nm,
    cm_mstr.cm_curr as curncy_cd,
    currency_cte.currencydescription as curncy_nm,
    cast(null as string) as indy_cd,
    cast(null as string) as indy_nm,
    cast(null as string) as intl_loc_nbr_check_digit,
    ad_mstr.ad_lang as lang_cd,
    cast(null as string) as lang_iso_cd,
    cast(null as string) as lang_nm,
    cast(null as string) as lgl_stat_cd,
    cast(null as string) as lgl_stat_nm,
    cast(null as string) as rgn_mkt,
    cast(null as string) as sls_since_yr,
    ad_mstr.ad_sort as sort_field,
    ad_mstr.ad_tax_usage as tax_juris_cd,
    cast(null as string) as tax_juris_nm,
    cast(null as string) as teletex_nbr,
    cast(null as string) as telex_nbr,
    cast(null as string) as title,
    cast(null as string) as transp_zone_cd,
    cast(null as string) as transp_zone_nm,
    cast(null as string) as trading_prtnr_co_cd,
    cast(null as string) as url,
    cast(null as string) as unload_point_flg,
    ad_mstr.ad_vat_reg as vat_regstr_nbr,
    cast(null as string) as central_del_block_flg,
    cast(null as string) as central_del_flg,
    cast(null as string) as central_post_block_flg,
    cast(null as string) as central_sls_block_flg,
    cast(null as string) as cmptr_flg,
    cast(null as string) as natural_pers_flg,
    cast(null as string) as one_time_cust_flg,
    cast(null as string) as sls_prtnr_flg,
    cast(null as string) as sls_prospect_flg,
    ad_mstr.ad_address_id as addr_key,
    ad_mstr.ad_line2 as street_line,
    ad_mstr.ad_zip as pstl_cd,
    ad_mstr.ad_city as city,
    cast(null as string) as city_coord,
    cast(null as string) as po_box,
    cast(null as string) as po_box_pstl_cd,
    cast(null as string) as district,
    ad_mstr.ad_state as st_prov_cd,
    cast(null as string) as st_prov_nm,
    ad_mstr.ad_ctry as cntry_cd,
    d_cntry_hier_cte.cntry_alpha2_cd as cntry_nm,
    ad_mstr.ad_fax as fax_nbr,
    cast(null as string) as trading_prtnr_co_nm,
    cast(null as string) as prim_contact_key,
    cast(null as string) as dnb_duns_nbr,
    ad_mstr.ad_line1 as addr_nm_line2,
    ad_mstr.ad_line2 as addr_nm_line3,
    ad_mstr.ad_line3 as addr_nm_line4,
    cast(null as string) as cust_cond_grp_cd1,
    cast(null as string) as cust_cond_grp_cd2,
    cast(null as string) as cust_cond_grp_nm1,
    cast(null as string) as cust_cond_grp_nm2,
    ad_mstr.ad_email as cust_email_addr_txt,
    cast(null as string) as cust_rept_hier_base,
    cast(null as string) as dw_src_key,
    cast(null as string) as indy_cd1,
    cast(null as string) as indy_cd2,
    cast(null as string) as indy_nm1,
    cast(null as string) as indy_nm2,
    cast(null as string) as intl_loc_nbr1,
    cast(null as string) as intl_loc_nbr2,
    ad_mstr.ad_phone as phn_nbr1,
    ad_mstr.ad_phone2 as phn_nbr2,
    cast(null as string) as search_mcode1,
    cast(null as string) as search_mcode2,
    cast(null as string) as search_mcode3,
    cast(null as string) as sply_center_cd,
    cast(null as string) as sply_center_flg,
    cast(null as string) as sply_center_nm,
    ad_mstr.ad_pst_id as tax_nbr1,
    cast(null as string) as tax_nbr2,
    cast(null as string) as tax_nbr3,
    cast(null as string) as src_crt_by,
    ad_mstr.ad_date as src_crt_ts,
    ad_mstr.ad_userid as src_updt_by,
    cm_mstr.cm_mod_date as src_updt_ts,
    current_timestamp as rec_crt_ts,
    current_timestamp as rec_updt_ts,
    cast(null as string) as stock_ticker_cd,
    cast(null as string) as cdw_cust_key,
    cast(null as string) as dw_cust_key,
    cast(null as string) as addr_phn_nbr,
    ad_mstr.ad_fax2 as addr_fax_nbr,
    cast(null as string) as sls_chnl_cd,
    cast(null as string) as sls_terr_cd,
    cast(null as string) as sls_rep_cust_key,
    cast(null as string) as addr_type_cd,
    cast(null as string) as hfm_entity_key,
    cast(null as string) as hfm_entity_cd,
    d_cntry_hier_cte.cntry_hier_key as deflt_delvr_cntry_key,
    ad_mstr.ad_ctry as deflt_delvr_cntry_cd,
    cast(null as string) as trade_chnl_cd,
    case 
        when ad_mstr.ad_addr like 'Z%' or ad_mstr.ad_addr like 'TM%' then 'IC'
        else '3rd'
    end as inter_co_cd,
    cast(null as string) as county,
    cast(null as string) as "temporary flag",
    cast(null as string) as "Bank Acct 1",
    cast(null as string) as "CoC Number",
    cast(null as string) as "Tax ID - Federal",
    cast(null as string) as "Tax Type",
    cast(null as string) as "Tax Class Code",
    cast(null as string) as "taxable flag",
    cast(null as string) as "tax in flag",
    cast(null as string) as "Netting Logic",
    cast(null as string) as "Trading Prtnr Interface ID",
    cast(null as string) as "EDI Control",
    cast(null as string) as "Time Zone",
    cast(null as string) as "Trading Prtnr EDI ID",
    cast(null as string) as "Barcode Label Print Program",
    cast(null as string) as "Barcode Validation Program",
    cast(null as string) as "Calendar",
    cast(null as string) as "EDI Standard",
    cast(null as string) as "EDI Standard Level",
    cast(null as string) as "Trd Partner Location Code",
    cast(null as string) as "Tax Zone",
    cast(null as string) as "Tax ID - Misc 1",
    cast(null as string) as "Tax ID - Misc 2",
    cast(null as string) as "Tax ID - Misc 3",
    cast(null as string) as "Week Offset",
    cast(null as string) as "Invoices Via",
    cast(null as string) as "Schedules Via",
    cast(null as string) as "Purchase Orders Via",
    cast(null as string) as "ASN Default Data",
    cast(null as string) as "IntraStat Division",
    cast(null as string) as "Tax Report Flag",
    cast(null as string) as "Name Control",
    cast(null as string) as "Last Filing Flag",
    cast(null as string) as "Priority",
    cast(null as string) as "Route",
    cast(null as string) as "Load Sequence",
    cast(null as string) as "Pick By Date",
    cast(null as string) as "Profile",
    cast(null as string) as "tac In City Flag",
    cast(null as string) as "Non-Sales Price List",
    cast(null as string) as "Business Relation",
    cast(null as string) as "Alternate UM",
    cast(null as string) as "City Code"
from cm_mstr_cte cm_mstr
left join ad_mstr_cte ad_mstr
    on upper(cm_mstr.cm_addr) = upper(ad_mstr.ad_addr)
    and upper(cm_mstr.cm_domain) = upper(ad_mstr.ad_domain)
left join currency_cte currency
    on currency.currencycode = cm_mstr.cm_curr
inner join d_cntry_hier_cte d_cntry_hier_cte
    on upper(ad_mstr.ad_ctry) = upper(d_cntry_hier_cte.cntry_alpha2_cd)
)
select
  concat('msd_qad_', lower(final_joined_cte.ad_domain)) || '|' || final_joined_cte.ad_addr as cust_key,
  concat('msd_qad_', lower(final_joined_cte.ad_domain)) as src_sys_cd,
  final_joined_cte.cm_addr as cust_id,
  final_joined_cte.ad_name as cust_nm,
  final_joined_cte.ad_name as cust_nm_en,
  final_joined_cte.ad_type as cust_type_cd,
  final_joined_cte.ad_type as cust_type_nm,
  cast(null as string) as active_flg,
  cast(null as string) as parent_cust_id,
  cast(null as string) as parent_cust_nm,
  cast(null as string) as naics_cd,
  cast(null as string) as naics_nm,
  cast(null as string) as sic_cd,
  cast(null as string) as sic_nm,
  cast(null as string) as gbl_govt_id,
  cast(null as string) as gbl_loc_nbr,
  cast(null as string) as dnb_duns_nm,
  cast(null as string) as alt_payer_cust_id,
  cast(null as string) as annl_sls_amt,
  cast(null as string) as central_bill_block_cd,
  cast(null as string) as central_bill_block_nm,
  cast(null as string) as central_delvr_block_cd,
  cast(null as string) as central_delvr_block_nm,
  cast(null as string) as central_ord_block_cd,
  cast(null as string) as central_ord_block_nm,
  cast(null as string) as cust_acct_grp_cd,
  cast(null as string) as cust_acct_grp_nm,
  cast(null as string) as cust_class_cd,
  cast(null as string) as cust_class_nm,
  final_joined_cte.cm_curr as curncy_cd,
  final_joined_cte.currencydescription as curncy_nm,
  cast(null as string) as indy_cd,
  cast(null as string) as indy_nm,
  cast(null as string) as intl_loc_nbr_check_digit,
  final_joined_cte.ad_lang as lang_cd,
  cast(null as string) as lang_iso_cd,
  cast(null as string) as lang_nm,
  cast(null as string) as lgl_stat_cd,
  cast(null as string) as lgl_stat_nm,
  cast(null as string) as rgn_mkt,
  cast(null as string) as sls_since_yr,
  final_joined_cte.ad_sort as sort_field,
  final_joined_cte.ad_tax_usage as tax_juris_cd,
  cast(null as string) as tax_juris_nm,
  cast(null as string) as teletex_nbr,
  cast(null as string) as telex_nbr,
  cast(null as string) as title,
  cast(null as string) as transp_zone_cd,
  cast(null as string) as transp_zone_nm,
  cast(null as string) as trading_prtnr_co_cd,
  cast(null as string) as url,
  cast(null as string) as unload_point_flg,
  final_joined_cte.ad_vat_reg as vat_regstr_nbr,
  cast(null as string) as central_del_block_flg,
  cast(null as string) as central_del_flg,
  cast(null as string) as central_post_block_flg,
  cast(null as string) as central_sls_block_flg,
  cast(null as string) as cmptr_flg,
  cast(null as string) as natural_pers_flg,
  cast(null as string) as one_time_cust_flg,
  cast(null as string) as sls_prtnr_flg,
  cast(null as string) as sls_prospect_flg,
  final_joined_cte.ad_address_id as addr_key,
  final_joined_cte.ad_line2 as street_line,
  final_joined_cte.ad_zip as pstl_cd,
  final_joined_cte.ad_city as city,
  cast(null as string) as city_coord,
  cast(null as string) as po_box,
  cast(null as string) as po_box_pstl_cd,
  cast(null as string) as district,
  final_joined_cte.ad_state as st_prov_cd,
  cast(null as string) as st_prov_nm,
  final_joined_cte.ad_ctry as cntry_cd,
  final_joined_cte.ad_country as cntry_nm,
  final_joined_cte.ad_fax as fax_nbr,
  cast(null as string) as trading_prtnr_co_nm,
  cast(null as string) as prim_contact_key,
  cast(null as string) as dnb_duns_nbr,
  final_joined_cte.ad_line1 as addr_nm_line2,
  final_joined_cte.ad_line2 as addr_nm_line3,
  final_joined_cte.ad_line3 as addr_nm_line4,
  cast(null as string) as cust_cond_grp_cd1,
  cast(null as string) as cust_cond_grp_cd2,
  cast(null as string) as cust_cond_grp_nm1,
  cast(null as string) as cust_cond_grp_nm2,
  final_joined_cte.ad_email as cust_email_addr_txt,
  cast(null as string) as cust_rept_hier_base,
  cast(null as string) as dw_src_key,
  cast(null as string) as indy_cd1,
  cast(null as string) as indy_cd2,
  cast(null as string) as indy_nm1,
  cast(null as string) as indy_nm2,
  cast(null as string) as intl_loc_nbr1,
  cast(null as string) as intl_loc_nbr2,
  final_joined_cte.ad_phone as phn_nbr1,
  final_joined_cte.ad_phone2 as phn_nbr2,
  cast(null as string) as search_mcode1,
  cast(null as string) as search_mcode2,
  cast(null as string) as search_mcode3,
  cast(null as string) as sply_center_cd,
  cast(null as string) as sply_center_flg,
  cast(null as string) as sply_center_nm,
  final_joined_cte.ad_pst_id as tax_nbr1,
  cast(null as string) as tax_nbr2,
  cast(null as string) as tax_nbr3,
  cast(null as string) as src_crt_by,
  final_joined_cte.ad_date as src_crt_ts,
  final_joined_cte.ad_userid as src_updt_by,
  final_joined_cte.cm_mod_date as src_updt_ts,
  current_timestamp as rec_crt_ts,
  current_timestamp as rec_updt_ts,
  cast(null as string) as stock_ticker_cd,
  cast(null as string) as cdw_cust_key,
  cast(null as string) as dw_cust_key,
  cast(null as string) as addr_phn_nbr,
  final_joined_cte.ad_fax2 as addr_fax_nbr,
  cast(null as string) as sls_chnl_cd,
  cast(null as string) as sls_terr_cd,
  cast(null as string) as sls_rep_cust_key,
  cast(null as string) as addr_type_cd,
  cast(null as string) as hfm_entity_key,
  cast(null as string) as hfm_entity_cd,
  final_joined_cte.cntry_hier_key as deflt_delvr_cntry_key,
  final_joined_cte.ad_ctry as deflt_delvr_cntry_cd,
  cast(null as string) as trade_chnl_cd,
  case when final_joined_cte.ad_addr like 'Z%' or final_joined_cte.ad_addr like 'TM%' then 'IC' else '3rd' end as inter_co_cd,
  cast(null as string) as county,
  cast(null as string) as temporary_flag,
  cast(null as string) as bank_acct_1,
  cast(null as string) as coc_number,
  cast(null as string) as tax_id_federal,
  cast(null as string) as tax_type,
  cast(null as string) as tax_class_code,
  cast(null as string) as taxable_flag,
  cast(null as string) as tax_in_flag,
  cast(null as string) as netting_logic,
  cast(null as string) as trading_prtnr_interface_id,
  cast(null as string) as edi_control,
  cast(null as string) as time_zone,
  cast(null as string) as trading_prtnr_edi_id,
  cast(null as string) as barcode_label_print_program,
  cast(null as string) as barcode_validation_program,
  cast(null as string) as calendar,
  cast(null as string) as edi_standard,
  cast(null as string) as edi_standard_level,
  cast(null as string) as trd_partner_location_code,
  cast(null as string) as tax_zone,
  cast(null as string) as tax_id_misc_1,
  cast(null as string) as tax_id_misc_2,
  cast(null as string) as tax_id_misc_3,
  cast(null as string) as week_offset,
  cast(null as string) as invoices_via,
  cast(null as string) as schedules_via,
  cast(null as string) as purchase_orders_via,
  cast(null as string) as asn_default_data,
  cast(null as string) as intrastat_division,
  cast(null as string) as tax_report_flag,
  cast(null as string) as name_control,
  cast(null as string) as last_filing_flag,
  cast(null as string) as priority,
  cast(null as string) as route,
  cast(null as string) as load_sequence,
  cast(null as string) as pick_by_date,
  cast(null as string) as profile,
  cast(null as string) as tac_in_city_flag,
  cast(null as string) as non_sales_price_list,
  cast(null as string) as business_relation,
  cast(null as string) as alternate_um,
  cast(null as string) as city_code
from final_joined_cte;